# Generated by Django 2.1.7 on 2019-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tên')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('title', models.CharField(max_length=50, verbose_name='Tiêu đề ')),
                ('content', models.TextField(verbose_name='Nội dung nhắn gửi')),
            ],
        ),
    ]
