# Generated by Django 2.1.7 on 2019-05-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='product',
        ),
    ]
