# Generated by Django 2.1.7 on 2019-05-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_photo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.Product'),
            preserve_default=False,
        ),
    ]
