# Generated by Django 2.1.7 on 2019-05-08 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
