# Generated by Django 2.1.7 on 2019-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190508_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.PositiveIntegerField(default=36),
            preserve_default=False,
        ),
    ]
